### ISSUE TITLE
On constants in traits

### ISSUE THREAD

**Issue by sj-i** [stephenreay/php-rfcs#2]
@stephenreay 
Hello!

The July 19 Feature Freeze for PHP 8.2 is approaching!
Do you still have any motivations for constants in traits?
I found you were previously working on this by searching the internals logs.

I'd try to see what I can do about constants in traits before the 8.2 deadline for starting an RFC discussion on June 21, but I'll find something else if you're still trying to work on it!

Thanks!

**Comment by stephenreay** [comment]
Hi!

I'm glad to see someone else is interested in this. Honestly, if you have the time to work on an RFC for this, please do. @iluuu1994 had expressed some interest in helping with the implementation (C is not really in my wheelhouse), but I'm not sure if he's still able to help.

I'm happy to help if I can, but I don't realistically have the time to dedicate to driving it right now.

**Comment by sj-i** [comment]
@stephenreay 
Thanks for the reply!

Then if I can make some progress, I'll fork this repository and go on!

**Comment by realjjaveweb** [comment]
This is a great start, but could we also aim at allowing the constant override int he classes using the Trait? If it wouldn't be much work, that would be awesome.

**Comment by realjjaveweb** [comment]
@sj-i 

This is a great start, but could we also aim at allowing the constant override int he classes using the Trait? If it wouldn't be much work, that would be awesome.
